### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by SouthAlley** [DoingDog/rconvert#2]
###Start deduplicate same DOMAIN and DOMAIN-SUFFIX rule lines
Traceback (most recent call last):
  File "keyworddd.py", line 16, in <module>
    content = line.split(',')[1].strip()
IndexError: list index out of range

**Comment by DoingDog** [comment]
这个是在哪里运行的啊，应该是那个txt源文件内容有问题

**Comment by SouthAlley** [comment]
https://raw.githubusercontent.com/ConnersHua/RuleGo/master/Surge/Ruleset/Extra/Reject/Advertising.list，https://raw.githubusercontent.com/sve1r/Rules-For-Quantumult-X/develop/Rules/Services/Microsoft.list
这是两个都有这个问题，生产的文件内容为空的

**Comment by DoingDog** [comment]
已找到问题原因

**Comment by DoingDog** [comment]
[https://raw.githubusercontent.com/sve1r/Rules-For-Quantumult-X/develop/Rules/Services/Microsoft.list](https://raw.githubusercontent.com/ConnersHua/RuleGo/master/Surge/Ruleset/Extra/Reject/Advertising.list%EF%BC%8Chttps://raw.githubusercontent.com/sve1r/Rules-For-Quantumult-X/develop/Rules/Services/Microsoft.list)没有错误，可以正常处理。
[https://raw.githubusercontent.com/ConnersHua/RuleGo/master/Surge/Ruleset/Extra/Reject/Advertising.list](https://raw.githubusercontent.com/ConnersHua/RuleGo/master/Surge/Ruleset/Extra/Reject/Advertising.list%EF%BC%8Chttps://raw.githubusercontent.com/sve1r/Rules-For-Quantumult-X/develop/Rules/Services/Microsoft.list)有两处语法不规范导致脚本类型判断错误

**Comment by DoingDog** [comment]
```
=>DOMAIN-SUFFIX,ad.youku.com,REJECT
DOMAIN-SUFFIX,atm.youku.com
DOMAIN,ad.mobile.youku.com
DOMAIN,adx.op.cp18.ott.cibntv.net
DOMAIN,iyes.youku.com
DOMAIN,pl.cp31.ott.cibntv.net
=>DOMAIN,ykad-data.youku.com,REJECT
```

**Comment by DoingDog** [comment]
脚本已修改。

**Comment by SouthAlley** [comment]
https://raw.githubusercontent.com/dler-io/Rules/main/Surge/Surge%203/Provider/Microsoft.list
https://raw.githubusercontent.com/sve1r/Rules-For-Quantumult-X/develop/Rules/Services/Microsoft.list
发现是这两个有冲突，单独运行的话，都没问题。合并在一起就不行

###Start deduplicate same DOMAIN and DOMAIN-SUFFIX rule lines
Traceback (most recent call last):
  File "keyworddd.py", line 25, in <module>
    del lines[idx]
IndexError: list assignment index out of range
###Processing IPCIDRs
sed: xn.txt: No such file or directory
sed: xn.txt: No such file or directory
sed: xn.txt: No such file or directory

**Comment by DoingDog** [comment]
> https://raw.githubusercontent.com/dler-io/Rules/main/Surge/Surge%203/Provider/Microsoft.list https://raw.githubusercontent.com/sve1r/Rules-For-Quantumult-X/develop/Rules/Services/Microsoft.list 发现是这两个有冲突，单独运行的话，都没问题。合并在一起就不行
> 
> ###Start deduplicate same DOMAIN and DOMAIN-SUFFIX rule lines Traceback (most recent call last): File "keyworddd.py", line 25, in del lines[idx] IndexError: list assignment index out of range ###Processing IPCIDRs sed: xn.txt: No such file or directory sed: xn.txt: No such file or directory sed: xn.txt: No such file or directory



已修复

**Comment by SouthAlley** [comment]
感谢，可以正常运行了
