### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by SouthAlley** [DoingDog/rconvert#3]
无法正常访问https://ruleset.isagood.day/ruleset.html下载
好像是加了人机验证
Downloaded
https://ruleset.isagood.day/global_domain.conf:
2023-12-11 13:24:45 ERROR 403: Forbidden.
https://ruleset.isagood.day/stream.conf:
2023-12-11 13:24:44 ERROR 403: Forbidden.

**Comment by DoingDog** [comment]
已删除了这些规则
